Resolve app cannot be deploy issue
Error: app.yaml not found
This is to do with mavern, so check the pom file,
under packaging tag
since we use kotlin for interface, it should be war.
If we use java, it should be jar